from random import *
fivesil= ["Just what is a horse", "A catastrophe","Looking foward to", "I'd fight them to hell","Have fun with that, LOL", "What's up with horses?","The veil hides their sins","What the hell are you", "I eat carrots","Tag with plague spririts", "Because screw horses","mortality blows", "Let me fight that horse", "Please, let it be me","Have you been inside","To live is to breathe", "The Earth our mother", "Global warming sucks", "Easily impressed", "Haiku's not funny","When I run across a haiku", "Count the syllables", " I wake, reluctant", "But, I need to pee", "How much can I fit","Oh no, I'm out of", "No,no,no,no,no", "Are you kidding me", "I will mess you up","Ignore my sobbing" "you never feed me", "that will show you","Practice makes perfect", "In trauma, time stops", "part of me falls through" , "Hoodlums punch my face"]

fivesil2= ["Fat man sees small door","save me, before they","always to be squashed","I screwed up big","tears flow free now","they would have made more sense","No,no,no,no,no","help me, I'm trapped","That is cute as fuck","all men are douches", "squish squash sling that slang", "Of her loneliness", "A grumpasaurus","Behold a small bird", "Godzilla must go"]

sevensil= ["A minimalist zebra", "Someone needs to kick its ass","You're it, and you're infections", "So then a horse can't eat them", "They're embodiments of sin", "Their eyelashes are too long", "Poisons hidden deep inside","I'm like a angry T-rex", "The future has a fever", "No,no,no,no,no,no,no", "Where did the semester go", "Too cold to get out of bed", "Into haiku format", "People laugh even though the", "The nice thing about spelling", "My hands are on the bookstore door", "Enchantment fills the cupboard","country goat got thrown into the","A wild night of lunacy", "In its weave is ripped a hole", "Who the hell threw that blue shell","In a haiku factory", "perhaps I'll sleep on your face","Ha, Ha, Ha, I don't think so", "I leap into the window", "Don't touch me! I am the night!", "Lying lifeless on the floor", "will eat almost anything", " A shot gun is  a good start", "What stockholm syndrome looks like", "And now it is too awkward", "Could make toilet paper thieves", "I would smite them if I could"]
rand_f= randint(0, len(fivesil)-1)
rand_s= randint(0, len(sevensil)-1)
rand_f2= randint(0, len(fivesil2)-1)
haiku= fivesil[rand_f]+"\n"+sevensil[rand_s]+"\n"+fivesil2[rand_f2]
print(haiku)
